
create table Players(
    ID VARCHAR(16) NOT NULL UNIQUE,
    PLAYER_NAME VARCHAR(255) NOT NULL,
    INDEX CHAR DEFAULT ''
);

create table Hall_Of_Famers(
    ID VARCHAR(16) PRIMARY KEY
);
create table Active_Players(
    ID VARCHAR(16) PRIMARY KEY
);

create table Player_Positions(
    ID VARCHAR(16) PRIMARY KEY,
    POSITIONS VARCHAR(255) DEFAULT ''
);
create table Player_Ages(
    ID VARCHAR(16) NOT NULL,
    YEAR INT, AGE INT,
    CONSTRAINT Unique_Ages UNIQUE (ID, YEAR)
);
create table Standard_Fielding_Stats(
    ID VARCHAR(16) NOT NULL,
    POSITION VARCHAR(3),
    YEAR INT, G INT, GS INT, CG INT, INN_DEF FLOAT, CHANCES INT, PO INT, A INT, E_DEF INT, DP_DEF INT, 
    FIELDING_PERC FLOAT, RANGE_FACTOR_PER_NINE FLOAT, RANGE_FACTOR_PER_GAME FLOAT, FIELDING_PERC_LG FLOAT, RANGE_FACTOR_PER_NINE_LG FLOAT,
    RANGE_FACTOR_PER_GAME_LG FLOAT, SB INT, CS INT, CAUGHT_STEALING_PERC FLOAT, CAUGHT_STEALING_PERC_LG FLOAT, PICKOFFS INT,
    CONSTRAINT Unique_Fielding UNIQUE (ID, POSITION, YEAR)
);
create table Career_Standard_Fielding_Stats(
    ID VARCHAR(16) NOT NULL,
    POSITION VARCHAR(3),
    G INT, GS INT, CG INT, INN_DEF FLOAT, CHANCES INT, PO INT, A INT, E_DEF INT, DP_DEF INT, 
    FIELDING_PERC FLOAT, RANGE_FACTOR_PER_NINE FLOAT, RANGE_FACTOR_PER_GAME FLOAT, FIELDING_PERC_LG FLOAT, RANGE_FACTOR_PER_NINE_LG FLOAT,
    RANGE_FACTOR_PER_GAME_LG FLOAT, SB INT, CS INT, CAUGHT_STEALING_PERC FLOAT, CAUGHT_STEALING_PERC_LG FLOAT, PICKOFFS INT,
    CONSTRAINT Career_Unique_Fielding UNIQUE (ID, POSITION)
);
create table Standard_Pitching_Stats(
    ID VARCHAR(16) NOT NULL,
    YEAR INT, W INT, L INT, WIN_LOSS_PERC FLOAT, EARNED_RUN_AVG FLOAT, G INT, GS INT, GF INT, CG INT, SHO INT, SV INT, 
    IP FLOAT, H INT, R INT, ER INT, HR INT, BB INT, IBB INT, SO INT, HBP INT, BK INT, WP INT, BATTERS_FACED INT, EARNED_RUN_AVG_PLUS FLOAT,
    FIP FLOAT, WHIP FLOAT, HITS_PER_NINE FLOAT, HOME_RUNS_PER_NINE FLOAT, BASES_ON_BALLS_PER_NINE FLOAT, STRIKEOUTS_PER_NINE FLOAT, STRIKEOUTS_PER_BASE_ON_BALLS FLOAT,
    CONSTRAINT Unique_Pitching UNIQUE (ID, YEAR)
);
create table Career_Standard_Pitching_Stats(
    ID VARCHAR(16) PRIMARY KEY,
    W INT, L INT, WIN_LOSS_PERC FLOAT, EARNED_RUN_AVG FLOAT, G INT, GS INT, GF INT, CG INT, SHO INT, SV INT, 
    IP FLOAT, H INT, R INT, ER INT, HR INT, BB INT, IBB INT, SO INT, HBP INT, BK INT, WP INT, BATTERS_FACED INT, EARNED_RUN_AVG_PLUS FLOAT,
    FIP FLOAT, WHIP FLOAT, HITS_PER_NINE FLOAT, HOME_RUNS_PER_NINE FLOAT, BASES_ON_BALLS_PER_NINE FLOAT, STRIKEOUTS_PER_NINE FLOAT, STRIKEOUTS_PER_BASE_ON_BALLS FLOAT
);
create table Awards(
    ID VARCHAR(16) NOT NULL,
    YEAR INT,
    AWARD VARCHAR(16) NOT NULL,
    CONSTRAINT Unique_Award UNIQUE (ID, YEAR, AWARD)
);
create table Standard_Hitting_Stats(
    ID VARCHAR(16) NOT NULL,
    YEAR INT, G INT, PA INT, AB INT, R INT, H INT, DOUBLES INT,
    TRIPLES INT, HR INT, RBI INT, SB INT, CS INT, BB INT, SO INT,
    BATTING_AVG FLOAT, ONBASE_PERC FLOAT, SLUGGING_PERC FLOAT, ONBASE_PLUS_SLUGGING FLOAT, ONBASE_PLUS_SLUGGING_PLUS INT, 
    TB INT, GIDP INT, HBP INT, SH INT, SF INT, IBB INT,
    CONSTRAINT Unique_Batting UNIQUE (ID, YEAR)
);
create table Career_Standard_Hitting_Stats(
    ID VARCHAR(16) PRIMARY KEY,
    G INT, PA INT, AB INT, R INT, H INT, DOUBLES INT,
    TRIPLES INT, HR INT, RBI INT, SB INT, CS INT, BB INT, SO INT,
    BATTING_AVG FLOAT, ONBASE_PERC FLOAT, SLUGGING_PERC FLOAT, ONBASE_PLUS_SLUGGING FLOAT, ONBASE_PLUS_SLUGGING_PLUS INT, 
    TB INT, GIDP INT, HBP INT, SH INT, SF INT, IBB INT
);



/** This table contains the HOF inductions information: inducted as, who inducted them, and amount of votes if applicable **/
create table Hall_Of_Fame_Stats_Induction(
    ID VARCHAR(16) NOT NULL,
    YEAR INT, CATEGORY_HOF VARCHAR(32), VOTED_BY VARCHAR(64), VOTES FLOAT, VOTES_PCT FLOAT,
    CONSTRAINT Unique_HOF_Inductions UNIQUE (ID, YEAR)
);

/** This table contains all the voting history from the BBWAA, Veterans, and Negro League ballots **/
create table Hall_Of_Fame_Stats_Ballots(
    ID VARCHAR(16) NOT NULL,
    YEAR INT, VOTED_BY VARCHAR(64), VOTES FLOAT, VOTES_PCT FLOAT,
    CONSTRAINT Unique_HOF_Ballots UNIQUE (ID, YEAR)
);